#!/bin/sh

SELECTION=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}
DND="dragon"
DND_ARG="-a -x -T"

[ -s "$SELECTION" ] &&
  TARGET=$(sed -z 's|'"$PWD/"'| |g;' < "$SELECTION") ||
  TARGET="$1"

eval setsid -f "$DND" "$DND_ARG" "$TARGET" &&
  printf "-" > "$NNN_PIPE"
