#!/bin/sh
#
## custom opener for nnn
## use xdg-open default if it has one

mimetype="$(file -bL --mime-type -- "${1}")"

case "$mimetype" in
  */pdf |\
  */vnd.djvu*)
    opener="zathura"
    ;;
  image/*)
    opener="devour siv"
    ;;
  video/*)
    opener="devour mpv"
    ;;
  *)
    opener="nvim"
    ;;
esac

$opener "$1"
