#!/bin/sh
#
## custom opener for nnn

mimetype="$(file -bL --mime-type -- "$1")"

case "$mimetype" in
  */pdf |\
  */vnd.djvu*)
    opener="zathura"
    ;;
  image/*)
    opener="swallow siv"
    ;;
  video/* |\
  audio/*)
    opener="swallow mpv"
    ;;
  application/x-rar |\
  application/zip)
    if [ "${1##*.}" = "cbr" ] || [ "${1##*.}" = "cbz" ] ; then
      opener="zathura"
    fi
    ;;
  *)
    opener="$EDITOR"
    ;;
esac

if [ "$opener" = "swallow siv" ] && [ -s "$NNN_SEL" ]; then
  xargs -0 swallow nsxiv -b -s d -a < "$NNN_SEL"
else
  $opener "$1"
fi
