#!/bin/sh
#
## custom opener for nnn

mimetype="$(file -bL --mime-type -- "$1")"

case "$mimetype" in
  */pdf |\
  */vnd.djvu*)
    opener="zathura"
    ;;
  image/*)
    opener="swallow siv"
    ;;
  video/* |\
  audio/*)
    opener="swallow mpv"
    ;;
  *)
    opener="$EDITOR"
    ;;
esac

$opener "$1"
